#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Script generated by Vivado on Sat Jul 29 14:43:00 CST 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# Tool Version Limit: 2023.05 
#
# Filename     : design_1.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the Xilinx simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip xpm gtwizard_ultrascale_v1_7_16 xil_defaultlib blk_mem_gen_v8_4_6 xdma_v4_1_23 xlslice_v1_0_2 xbip_utils_v3_0_10 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_15 c_gate_bit_v12_0_6 xbip_counter_v3_0_6 c_counter_binary_v12_0_16 xlconstant_v1_1_7 microblaze_v11_0_11 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 lmb_v10_v3_0_12 lmb_bram_if_cntlr_v4_0_22 iomodule_v3_1_8 util_vector_logic_v2_0_2 generic_baseblocks_v2_1_0 fifo_generator_v13_2_8 axi_data_fifo_v2_1_27 axi_infrastructure_v1_1_0 axi_clock_converter_v2_1_27)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2023.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/home/alinx/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "/home/alinx/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vlogan -work gtwizard_ultrascale_v1_7_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/102d/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/sim/design_1_xdma_0_0_pcie4c_ip_gt_gthe4_channel_wrapper.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_common.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/sim/design_1_xdma_0_0_pcie4c_ip_gt_gthe4_common_wrapper.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/sim/design_1_xdma_0_0_pcie4c_ip_gt_gtwizard_gthe4.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/sim/design_1_xdma_0_0_pcie4c_ip_gt_gtwizard_top.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/ip_0/sim/design_1_xdma_0_0_pcie4c_ip_gt.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_cxs_remap.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram_16k_int.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram_16k.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram_32k.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram_4k_int.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram_msix.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram_rep_int.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram_rep.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram_tph.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_bram.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gtwizard_top.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_phy_ff_chain.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_phy_pipeline.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_gt_channel.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_gt_common.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_phy_clk.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_phy_rst.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_phy_rxeq.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_phy_txeq.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_sync_cell.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_sync.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_cdr_ctrl_on_eidle.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_receiver_detect_rxterm.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_gt_phy_wrapper.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_phy_top.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_init_ctrl.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_pl_eq.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_vf_decode.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_vf_decode_attr.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_pipe.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_seqnum_fifo.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_sys_clk_gen_ps.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source/design_1_xdma_0_0_pcie4c_ip_pcie4c_uscale_core_top.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/sim/design_1_xdma_0_0_pcie4c_ip.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work blk_mem_gen_v8_4_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_1/sim/xdma_v4_1_23_blk_mem_64_reg_be.v" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/ip_2/sim/xdma_v4_1_23_blk_mem_64_noreg_be.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xdma_v4_1_23 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/xdma_v4_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/xdma_v4_1/hdl/verilog/design_1_xdma_0_0_dma_bram_wrap.sv" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/xdma_v4_1/hdl/verilog/design_1_xdma_0_0_dma_bram_wrap_1024.sv" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/xdma_v4_1/hdl/verilog/design_1_xdma_0_0_dma_bram_wrap_2048.sv" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/xdma_v4_1/hdl/verilog/design_1_xdma_0_0_core_top.sv" \
  "../../../bd/design_1/ip/design_1_xdma_0_0/sim/design_1_xdma_0_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_util_ds_buf_0/util_ds_buf.vhd" \
  "../../../bd/design_1/ip/design_1_util_ds_buf_0/sim/design_1_util_ds_buf_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlslice_0_0/sim/design_1_xlslice_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/5a54/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_addsub_v12_0_15 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/6b20/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_gate_bit_v12_0_6 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/7161/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xbip_counter_v3_0_6 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/9ac8/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work c_counter_binary_v12_0_16 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/5421/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_c_counter_binary_0_0/sim/design_1_c_counter_binary_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/b0f2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_xlconstant_1_0/sim/design_1_xlconstant_1_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work microblaze_v11_0_11 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/e224/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_0/sim/bd_45eb_microblaze_I_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_1/sim/bd_45eb_rst_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lmb_v10_v3_0_12 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/cd1d/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_2/sim/bd_45eb_ilmb_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_3/sim/bd_45eb_dlmb_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work lmb_bram_if_cntlr_v4_0_22 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/b87e/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_4/sim/bd_45eb_dlmb_cntlr_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_5/sim/bd_45eb_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_6/sim/bd_45eb_lmb_bram_I_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_7/sim/bd_45eb_second_dlmb_cntlr_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_8/sim/bd_45eb_second_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_9/sim/bd_45eb_second_lmb_bram_I_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work iomodule_v3_1_8 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/b8f2/hdl/iomodule_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/ip/ip_10/sim/bd_45eb_iomodule_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/bd_0/sim/bd_45eb.v" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_0/sim/design_1_ddr4_0_0_microblaze_mcs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/phy/design_1_ddr4_0_0_phy_ddr4.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy_behav.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob_byte.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/iob/ddr4_phy_v2_2_iob.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/clocking/ddr4_phy_v2_2_pll.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_tristate_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_riuor_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_control_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_byte_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_bitslice_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/ip_top/design_1_ddr4_0_0_phy.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_wtr.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ref.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_rd_wr.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_periodic.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_group.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_merge_enc.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_gen.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_fi_xor.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_dec_fix.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc_buf.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ecc.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_ctl.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_c.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_cmd_mux_ap.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_p.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_mux_p.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_c.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_arb_a.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_timer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc_act_rank.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/controller/ddr4_v2_2_mc.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_wr_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_rd_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ui/ddr4_v2_2_ui_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ui/ddr4_v2_2_ui.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_ar_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_aw_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_b_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_arbiter.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_fsm.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_cmd_translator.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_fifo.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_incr_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_r_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_w_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wr_cmd_fsm.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_wrap_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_a_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_register_slice.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axi_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_axic_register_slice.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_and.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_and.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_latch_or.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_carry_or.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_command_fifo.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_comparator_sel_static.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_r_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi/ddr4_v2_2_w_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_addr_decode.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_read.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg_bank.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_top.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_write.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/clocking/ddr4_v2_2_infrastructure.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_bram.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_write.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_byte.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_wr_bit.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_sync.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_read.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_rd_en.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_pi.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_mc_odt.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_debug_microblaze.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_cplx.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_config_rom.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_addr_decode.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_top.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal_xsdb_arbiter.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_cal.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_chipscope_xsdb_slave.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/ddr4_v2_2_dp_AB9.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top/design_1_ddr4_0_0_ddr4.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top/design_1_ddr4_0_0_ddr4_mem_intfc.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal/design_1_ddr4_0_0_ddr4_cal_riu.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top/design_1_ddr4_0_0.sv" \
  "../../../bd/design_1/ip/design_1_ddr4_0_0/tb/design_1_ddr4_0_0_microblaze_mcs_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work util_vector_logic_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_util_vector_logic_0_0/sim/design_1_util_vector_logic_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/design_1/ip/design_1_proc_sys_reset_0_0/sim/design_1_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work fifo_generator_v13_2_8 $vhdlan_opts \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work fifo_generator_v13_2_8 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_data_fifo_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_s00_data_fifo_0/sim/design_1_s00_data_fifo_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_clock_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/29db/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"$ref_dir/../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_xdma_0_0/ip_0/source" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/03b2/hdl/verilog" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/ip_1/rtl/map" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/ip_top" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ip/design_1_ddr4_0_0/rtl/cal" +incdir+"../../../../pcie_test.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"/home/alinx/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/design_1/ip/design_1_auto_cc_0/sim/design_1_auto_cc_0.v" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/media/alinx/nvme4t/xie/au15p/pcie_test_ddr/pcie_test.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc design_1_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
